server:
    port: 9004

spring:
  rabbitmq:
    password: guest
    port: '5672'
    host: localhost
    username: guest
queue:
  arriving-plane: ArrivingPlaneQueue
  update-arriving-plane: UpdateArrivingPlaneQueue
  landing-confirmation: LandingConfirmationQueue
  refuel-plane: RefuelPlaneQueue